name: ps

services:
  api:
    build:
      context: ../
      dockerfile: .dev/Dockerfile
    env_file:
      - ../.env
    ports:
      - 8000:80
      - 5678:5678
    depends_on:
      - db
    volumes:
      - ../:/app
    container_name: ps-api
  db:
    image: postgres:16.2-alpine
    restart: unless-stopped
    ports:
      - 5432:5432
    volumes:
      - ps_db_data:/var/lib/postgresql/data/
    environment:
      POSTGRES_USER: postgres
      POSTGRES_DB: postgres
      POSTGRES_PASSWORD: postgres
    container_name: ps-api-db
volumes:
  ps_db_data:
